name: bluetooth_print
description: fork from bluetooth_print BluetoothPrint is a bluetooth plugin to help developers build bluetooth thermal printer apps for both iOS and Android.
version: 4.2.4
homepage: https://github.com/xiaoq7758/bluetooth_print

environment:
  sdk: ">=3.0.0 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.8.0


flutter:
  plugin:
    platforms:
      android:
        package: com.example.bluetooth_print
        pluginClass: BluetoothPrintPlugin
      ios:
        pluginClass: BluetoothPrintPlugin